//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Football
{
    using System;
    using System.Collections.Generic;
    
    public partial class Match
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Match()
        {
            this.Tickets = new HashSet<Ticket>();
            this.Timetables = new HashSet<Timetable>();
        }
    
        public int id { get; set; }
        public int stadiumID { get; set; }
        public int hostID { get; set; }
        public int guestID { get; set; }
        public int mainRefereeID { get; set; }
        public int technicalRefereeID { get; set; }
        public int linesRefereeID { get; set; }
        public int observerRefereeID { get; set; }
        public int hostGoals { get; set; }
        public int guestGoals { get; set; }
    
        public virtual Club Club { get; set; }
        public virtual Club Club1 { get; set; }
        public virtual Stadium Stadium { get; set; }
        public virtual Referee Referee { get; set; }
        public virtual Referee Referee1 { get; set; }
        public virtual Referee Referee2 { get; set; }
        public virtual Referee Referee3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ticket> Tickets { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Timetable> Timetables { get; set; }
    }
}
