//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Football
{
    using System;
    using System.Collections.Generic;
    
    public partial class Winner
    {
        public int id { get; set; }
        public int clubID { get; set; }
        public string year { get; set; }
        public int wonMatches { get; set; }
        public int lostMatches { get; set; }
        public int goalsScored { get; set; }
        public int goalsLost { get; set; }
    
        public virtual Club Club { get; set; }
    }
}
